### ISSUE TITLE
Numba error

### ISSUE THREAD

**Issue by and-tos** [bio-phys/PyDHAMed#8]
Dear Lukas,
thanks a lot for providing the software to DHAMed. 
I am trying to use the program with the following test data:

traj=np.array([0., 0., 1., 2., 1., 0., 2., 2.])
c_l = [count_matrix(traj,n_states=3)]
v_ar=np.array([1, 1.5, 2]).reshape(3,1)

I get the following error:

File "dhamed.py", line 17, in <module>
    bl_g = run_dhamed(c_l, -np.log(v_ar))
....
....
InternalError: unsupported array index type float64 in [float64]
[1] During: typing of intrinsic-call at /home/andt88/miniconda2/lib/python2.7/site-packages/pydhamed/optimize_dhamed.py (21)
--%<-----------------------------------------------------------------

File "../../../../miniconda2/lib/python2.7/site-packages/pydhamed/optimize_dhamed.py", line 21

**Comment by kain88-de** [comment]
Can you try `traj.astype(int)`?  I’m guessing some internal function doesn’t like that you used floats for the trajectory.

**Comment by lukas-stelzl** [comment]
Thanks @andt88 for trying out our package :). Does the problem persists with the trajectory converted to integers, following @kain88-de's suggestion? You can also try to switch off Numba setting  `jit_gradient=False` when calling `run_dhamed`.

**Comment by and-tos** [comment]
Thanks for you quick responses! Unfortunately it's still not working.
Here's the code I'm running:

```python
traj=np.array([0, 0, 1, 2, 1, 0, 2, 2])
c_l = [count_matrix(traj,n_states=3)]

v_ar=np.array([1, 1.5, 2]).reshape(3,1)
og = run_dhamed(c_l, -np.log(v_ar), numerical_gradients=False, jit_gradient=True)
n_blocks = 4
bl_l = []
for bl in np.split(traj[0:],n_blocks):
    bl.astype(int)
    c_l = [count_matrix(bl,n_states=3)]
    bl_g = run_dhamed(c_l, -np.log(v_ar), numerical_gradients=False, jit_gradient=True)
```


*edit kain88-de*: update code formatting

**Comment by kain88-de** [comment]
@andt88  The error should be fixed now in master.

You can always try a current version of the master branch with our new mybinder online.

https://mybinder.org/v2/gh/bio-phys/PyDHAMed/master

it will open a notebook server on the cloud you can use to test things. You might have to be patient for it to open up though (a minute or two occasionally).

**Comment by and-tos** [comment]
Thanks for fixing this! I am completely new to Jupyter Notebooks. How can I obtain the fixed program? Or can I just run it in the Jupyter environment for now?

**Comment by kain88-de** [comment]
You have to update your local copy. If you followed the instructions in the Readme that should be

```bash
cd PYyHAMed
git remote update
git rebase origin/master
pip install .
```

This should work in most cases.

**Comment by and-tos** [comment]
Sorry to bother again, but this is not working for me. I updated as described, but I am still getting the same error when running the code. Which python version should I run pyDHAMed with?

**Comment by and-tos** [comment]
I uninstalled and reinstalled it and it's working now!
